services:
  app:
    # pour utilisation dans github actions sans reconstruction de l'image
    image: ${IMAGE_NAME}
    build: 
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile
    volumes:
      - ./data:/project/data
    ports:
      - "8000:8000"
