global:
  scrape_interval: 15s

rule_files:
  - "alert.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'rakuten_fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]