from .pipeline_image_preprocess import pipeline_image_preprocess
from .pipeline_image_evaluate import pipeline_image_evaluate

from .pipeline_text_preprocess import pipeline_text_preprocess
from .pipeline_text_evaluate import pipeline_text_evaluate

from .pipeline_multimodel_train import pipeline_multimodel_train
from .pipeline_global import global_pipeline