name: FastAPI + Pytest Integration

on:
  push:
    branches: [ "fabrice_unittests" ]
  pull_request:
    branches: [ "fabrice_unittests" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      fastapi:
        image: python:3.12
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000/docs || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
        env:
          PYTHONUNBUFFERED: 1
        volumes:
          - ./:/source
        command: >
          sh -c "cd /source && pip install --upgrade pip &&
                 pip install -r requirements.txt &&
                 uvicorn app.main:app --host 0.0.0.0 --port 8000"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for FastAPI to be healthy
        env:
          BASE_URL: http://fastapi:8000
        run: |
          for i in {1..30}; do
            if curl -s $BASE_URL/docs; then
              echo "FastAPI is up!"
              exit 0
            fi
            echo "Waiting for FastAPI..."
            sleep 2
          done
          echo "FastAPI did not start in time."
          exit 1

      - name: Run pytest with BASE_URL
        env:
          BASE_URL: http://fastapi:8000
        run: pytest